### ISSUE TITLE
没有发布到 google store 或者生产 crx 文件吗

### ISSUE THREAD

**Issue by dwqs** [ghostcode/nodejs-api-tree#1]

**Comment by ghostcode** [comment]
已经提交crx，但是现在好像不能用crx安装了！如下图：

![snipaste_2018-04-06_08-12-02](https://user-images.githubusercontent.com/745181/38397839-76c0c3ec-3972-11e8-8919-26acf1bb275a.png)

不过可以用 https://greasyfork.org/zh-CN 这种方式安装。
