### ISSUE TITLE
打开 node.js 官网首页或者非 api 页面会报错

### ISSUE THREAD

**Issue by dwqs** [ghostcode/nodejs-api-tree#2]
报错信息如下：

```js
better-view.js:42 Uncaught TypeError: Cannot read property 'style' of null
    at better-view.js:42
```

对应代码：

![image](https://user-images.githubusercontent.com/7871813/38457516-edf2f5fa-3ac3-11e8-8264-fd961c0802d6.png)

在对相应的 dom 节点操作之前应该先判断节点存在与否

**Comment by ghostcode** [comment]
多谢，没有做严格的测试。已改：https://github.com/ghostcode/nodejs-api-tree/commit/f4eb67bddbf09d672d9d2011d0015f40a95cad8c
